### ISSUE TITLE
Websockets Disconnects after first message recieved ESP32 Generic Ethernet WS5

### ISSUE THREAD

**Issue by jacoherotel** [khoih-prog/WebSockets_Generic#34]
### Describe the bug

Using the standard example for Websockets2 Generic, and ESP32 with WZ500 shield as a **WebsocketServer**, everything works, excepts after first message the server closes the websocket.

### Steps to Reproduce
Compile and run the WebsocketServer Example under Generic, ESP32 Ethernet.

### Expected behavior

Like with normal Websockets library [Links2004](https://github.com/Links2004)
the socket should stay open until client disconnects or server kills the connection.

### Actual behavior

Server sends disconnect after first message received.

### Information

Please ensure to specify the following, or your post will be ignored and deleted:

This happens on any IDE, PlatformIO and Ardunio IDE.
Using latest espressif32, with platform arduino.
Nothing added, plain example. Tested from Chrome and several other browsers.

This happens on Wifi and Ethernet.

**Comment by khoih-prog** [comment]
Hi @jacoherotel 

You have to specify clearly the examples / steps you are using, better to include the [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example) as well as debug terminal outputs, so that anybody can see this is valid issue, then spend time to duplicate / verify.

Sorry, nobody will waste the time to read your mind / cryptic description.

I'm closing the issue now, and won't reopen until you post the requested info to validate the issue.
